### ISSUE TITLE
Fails to compile when using namespaces in less files

### ISSUE THREAD

**Issue by ablankenship10** [officert/css-important-loader#1]
Is this a bug or is there a specific order I should use this loader to make sure the less is compiled before this loader does its thing?

> ERROR in ./\~/css-loader?modules=true&localIdentName=[name]__[local]___[hash:base64:5]!./\~/less-loader/dist!./~/cssimportant-loader!./src/style/Loader.less
Module build failed: Error: undefined:2:3: missing '}'

LESS file:

```
.cleanslate {
  .default {
    opacity: 1;
    transition: all 1.2s;
  }

  .hide {
    opacity: 0;
  }
}
```

**Comment by nathan-charrois** [comment]
Same issue with SCSS, doesn't look like it supports nesting.

**Comment by officert** [comment]
@ablankenship10 and @NathanCH  you'll need to run it through the `css-loader` first to turn into valid CSS. 

something like:

`'style-loader', 'less-loader', 'css-loader', 'cssimportant-loader'`
