### ISSUE TITLE
Fails to compile with an empty ruleset

### ISSUE THREAD

**Issue by iarry** [officert/css-important-loader#2]
When I generate a new component it creates a scss file that looks like

```
.componentName{

}

```

If that file doesn't have any rules defined, it fails to compile. Commented them out and it compiles.

Was just a minor inconvenience since I only had 4 files like this - and it's a little nice that now I'm not including the unnecessary rulesets, however now I'll need to adjust my file template to comment out the definition by default so compilation doesn't fail before I add styles to my components.

EDIT: This doesn't appear to be the case when it's an empty ruleset nested inside of another (although this is still getting passed to the sass loader first - not sure what that output looks like).

**Comment by officert** [comment]
@iarry  I added a new test to try and reproduce the error you're getting:

https://github.com/officert/css-important-loader/commit/204c6f982001b9b38c8bd3ac8d731162c9df8643

But it doesn't seem to throw any errors and the test runs ok.

The test just tries to compile the following css:

```
.componentName{
}
```

Could you add in the error you were getting? maybe I'm missing something

Thanks!
